require('dotenv').config()
UPLOADCARE_PUBLIC_KEY = process.env.PUBLIC_KEY_UPLOADCARE;
UPLOADCARE_LOCALE = 'en';
UPLOADCARE_TABS = 'file';
UPLOADCARE_IMAGES_ONLY = true;
UPLOADCARE_PREVIEW_STEP = true;
